# Generated by Django 5.2 on 2025-08-11 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_subscribe", "0002_alter_subscribe_athlete_alter_subscribe_coach"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscribe",
            constraint=models.UniqueConstraint(
                fields=("athlete", "coach"), name="unique_subscribe"
            ),
        ),
    ]
