# Generated by Django 5.2 on 2025-07-28 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_run", "0008_remove_challenge_athlete_remove_position_run_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=4, max_digits=6)),
                ("longitude", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_run.run"
                    ),
                ),
            ],
        ),
    ]
