# Generated by Django 5.2 on 2025-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("app_positions", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="position",
            name="date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
