# Generated by Django 5.2 on 2025-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_positions", "0002_position_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="distance",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="position",
            name="speed",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
