# Generated by Django 5.2 on 2025-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("app_athletes", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="athleteinfo",
            name="goals",
            field=models.TextField(blank=True, default="", max_length=50),
        ),
    ]
