# Generated by Django 5.2 on 2025-07-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("app_run", "0003_athleteinfo"),
    ]

    operations = [  # noqa: RUF012
        migrations.RenameField(
            model_name="athleteinfo",
            old_name="user",
            new_name="user_id",
        ),
    ]
