# Generated by Django 5.2 on 2025-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("app_run", "0006_position"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="run",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
