# Generated by Django 5.2 on 2025-07-28 19:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("app_run", "0007_run_distance"),
    ]

    operations = [  # noqa: RUF012
        migrations.RemoveField(
            model_name="challenge",
            name="athlete",
        ),
        migrations.RemoveField(
            model_name="position",
            name="run",
        ),
        migrations.DeleteModel(
            name="AthleteInfo",
        ),
        migrations.DeleteModel(
            name="Challenge",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
    ]
