# Generated by Django 5.2 on 2025-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("app_run", "0008_remove_challenge_athlete_remove_position_run_and_more"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="run",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
