# Generated by Django 5.2 on 2025-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("app_run", "0009_alter_run_comment"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="run",
            name="run_time_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
