# Generated by Django 5.2 on 2025-08-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0010_run_run_time_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="speed",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
