# Generated by Django 5.2 on 2025-08-02 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("collectible_items", "0002_alter_collectibleitem_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="collectibleitem",
            name="athlete",
            field=models.ManyToManyField(
                related_name="collectible_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
